<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>license-gen</AssemblyName>
    <RootNamespace>LicenseGen</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <ApplicationIcon>..\..\src\NovaFiches\assets\NovaFiches.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
